#!/bin/zsh

# Use existing AWS_PROFILE or prompt for it
if [ -z "$AWS_PROFILE" ]; then
  read "AWS_PROFILE?Enter your AWS SSO profile name: "
  export AWS_PROFILE
else
  echo "Using existing AWS_PROFILE: $AWS_PROFILE"
fi

# Check if you're already logged in
if aws sts get-caller-identity --profile "$AWS_PROFILE" >/dev/null 2>&1; then
  echo "✅ Already logged in with AWS SSO for profile '$AWS_PROFILE'."
else
  echo "🔐 Logging in with AWS SSO for profile '$AWS_PROFILE'..."
  aws sso login --profile "$AWS_PROFILE"
fi

# Retrieve credentials from CLI cache
echo "🔄 Extracting temporary credentials..."

eval "$(aws configure export-credentials --format env)"

# Verify extraction
if [ -z "$AWS_ACCESS_KEY_ID" ] || [ -z "$AWS_SECRET_ACCESS_KEY" ] || [ -z "$AWS_SESSION_TOKEN" ]; then
  echo "❌ Failed to extract credentials for profile '$AWS_PROFILE'."
  exit 1
fi

# Set VITE_ prefixed variables for the React app
export VITE_AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID"
export VITE_AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY"
export VITE_AWS_SESSION_TOKEN="$AWS_SESSION_TOKEN"
export VITE_AWS_REGION="${AWS_DEFAULT_REGION:-us-east-1}"

# Create .env.local file for the React app
cat > .env.local << EOF
# AWS Credentials for Bedrock LLM Analyzer
# Generated by local-setup.sh at $(date)
# Profile: $AWS_PROFILE

VITE_AWS_REGION=${AWS_DEFAULT_REGION:-us-east-1}
VITE_AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
VITE_AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
VITE_AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN

# Note: These are temporary SSO credentials that will expire
EOF

# Output confirmation
echo ""
echo "✅ Environment variables set for terminal session"
echo "✅ Created .env.local file for React app"
echo "🚀 You can now run: npm run dev"
